### ISSUE TITLE
HTML pages / BL for  Finance Module

### ISSUE THREAD

**Issue by rehbarkhan** [rehbarkhan/ms#10]
##### Model name : FinanceStaff
 - first name
 - last name
 - dob
 - contact number
 - Address
 -  user - OnetoOneKey(CustomUser)
 -  finance Module (Boolean Filed = False) will map these to more specified filed latr

Finance Module:
 [ create the finance module for the mode will have meeting for this ]

**Comment by AnuragException** [comment]
Please provide description about the issue to work on.

**Comment by rehbarkhan** [comment]
Issue is nothing but task if we use GitHub Project Features and in this we are indeed using it.

**Comment by rehbarkhan** [comment]
I have just pushed some code for Admission Department, check those code it will give you an idea on how to create the module and then register a new member for Finance Department along with the User creation on go.
Remember , the final confirmation will go to dean and after his approval, the account will get activated.
